version: '3'
services:
  weremainfund.org:
    image: gcr.io/black-network-156417/weremainfund.org
    build:
      args:
        APP: weremainfund.org
        HTTP_PORT: 4200
        HTTPS_PORT: 4243
        NODE_ENV: ${NODE_ENV}
        ADMIN_EMAIL: kevin.davison@weremainfund.org
      context: .
      dockerfile: Dockerfile
    expose:
      - 4200
    ports:
      - "80:4200"
    volumes:
      - ./src:/srv/www/weremainfund.org/src
      - ./server:/srv/www/weremainfund.org/server
#    user: node
#    working_dir: /srv/www/weremainfund.org/
