# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '2'

services:
  web:
    build:
      dockerfile: .docker/production.dockerfile
    environment:
      NODE_ENV: 'production'
