version: '2'
services:
  weremainfund.org:
    image: weremainfund.org
    build:
      args:
        APP: weremainfund.org
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:4200"
      - "443:4200"
