version: '2'
services:
  wereamin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/wereamin
    links:
      - redis
  redis:
    image: redis
